version: '3.6'

services: 
  # database
  db:
    image: db
    build: 
      context: .
      dockerfile: docker/db/Dockerfile
    restart: always
    # command: --init-file /data/application/init.sql
    volumes:
      # - ./init.sql:/data/application/init.sql
      - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_DATABASE=golang"
      - "MYSQL_USER=saqsham"
      - "MYSQL_PASSWORD=1234"
      - "MYSQL_ROOT_PASSWORD=1234"
    ports:
      - "3306:3306"
    container_name: database.dev
    security_opt:
      - seccomp:unconfined
    networks:
      - mynetwork

  # app
  go-app:
    image: app
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    volumes: 
      - ./app-main:/go/src/app
    restart: always
    container_name: app.dev
    working_dir: /go/src/app
    command: go run server.go
    # command: ["./wait-for-it", "mysql:3306", "--", "go", "run", "server.go"]
    depends_on:
      - db
    links: 
      - db
    ports:
      - "3000:3000"
    networks:
      - mynetwork

# network
networks: 
  mynetwork:
    driver: bridge

  # proxy
  # proxy:
  #   image: nginx
  #   volumes: 
  #     - ./app-main/nginx.conf:/etc/nginx/conf.d/proxy.conf
  #   restart: always
  #   ports: 
  #     - "80:80"
  #     - "443:443"
  #   depends_on: 
  #     - go-app