version: '3.6'

services: 
  # mysql database
  db:
    image: db
    build: 
      context: .
      dockerfile: docker/db/Dockerfile
    restart: always
    # command: --init-file /data/application/init.sql
    volumes:
      - ../mysql_init:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_DATABASE=golang"
      - "MYSQL_USER=saqsham"
      - "MYSQL_PASSWORD=1234"
      - "MYSQL_ROOT_PASSWORD=1234"
    ports:
      - "3306:3306"
    container_name: database.dev
    security_opt:
      - seccomp:unconfined # not safe
    networks:
      - mynetwork

  # golang web app
  app:
    image: app
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    volumes: 
      - ../app-main:/go/src/app
    restart: always
    # container_name: app.dev
    working_dir: /go/src/app
    command: go run server.go
    depends_on:
      - db
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - PORT=:3000
    networks:
      - mynetwork

# network
networks: 
  mynetwork:
    driver: bridge
      